"""AI decision journal: persistence, outcome reconciliation, and metrics.

Extracted verbatim from ``orchestrator.py`` -- every method's AST is unchanged;
only the enclosing class moved.  ``QuadOrchestrator`` keeps all three methods
with their original signatures.

The three belong together because they are one pipeline: ``_log_ai_decision``
writes each decision, ``_reconcile_decision_outcomes`` later resolves whether
it paid off, and ``_compute_ai_metrics`` aggregates both into the Prometheus
gauges.  Splitting them across modules would only hide that relationship.
"""

from __future__ import annotations

import time
from typing import Any


class DecisionJournalMixin:
    """Decision persistence, reconciliation, and derived AI metrics.

    The attributes below are the state this mixin *consumes*.  They are
    declared rather than assigned, so the mixin documents the contract it
    expects from its host class without owning it.
    """

    _log: Any
    _config_dict: Any
    _db_manager: Any
    _metrics: Any
    _last_ai_cycle_time_ms: Any
    _metrics_cycle_count: Any

    async def _log_ai_decision(
        self,
        decision: dict[str, Any],
        context: Any,
    ) -> int | None:
        """Log an AI decision to the database DecisionModel table.

        Returns the generated ``decision_id`` (or ``None`` when the DB is
        unavailable / the INSERT failed) so callers can later mark the row
        as ``executed=1`` after a confirmed fill.
        """
        if self._db_manager is None:
            return None

        from quad.persistence.models import DecisionModel
        from quad.persistence.repositories import DecisionRepository, make_repo

        repo = make_repo(DecisionRepository, self._db_manager, self._config_dict)
        try:
            # Confidence arrives as a float after normalize_decision, but the
            # legacy path may carry a raw string; coerce defensively.
            try:
                confidence = float(decision.get("confidence") or 0.0)
            except (TypeError, ValueError):
                confidence = 0.0
            action = decision.get("action") or "HOLD"
            symbol = decision.get("contract") or ""
            # Phase 3: capture the mark price at decision time for ENTER
            # decisions so realized PnL / exit can be computed later once a
            # close source exists.  ``context.mark_prices`` is keyed by pair
            # symbol and is already available without an extra API call.
            entry_price = ""
            if action == "ENTER":
                try:
                    mark_prices = getattr(context, "mark_prices", None) or {}
                    entry_price = str(mark_prices.get(symbol) or "")
                except Exception:
                    entry_price = ""
            decision_id = await repo.create(
                DecisionModel(
                    id=0,  # auto-generated by AUTOINCREMENT
                    timestamp=int(time.time()),
                    # The AI JSON may carry an EXPLICIT null for these fields
                    # (e.g. `"strategy": "trend_following" | null`). `dict.get()`
                    # returns that null instead of the fallback, which would
                    # violate the NOT NULL columns in `decisions` DDL.  Coerce
                    # null-ish values (None / "") back to the fallback here so
                    # the repository INSERT never hits the constraint.
                    strategy=decision.get("strategy") or "ai_default",
                    action=action,
                    symbol=symbol,
                    reason=(decision.get("reasoning") or "")[:500],
                    risk_passed=1 if action in ("ENTER", "EXIT") else 0,
                    executed=0,
                    cycle_time_ms=int(self._last_ai_cycle_time_ms),
                    # Phase 1 fields: predicted direction + plausibility gate.
                    predicted_direction=decision.get("direction") or "NEUTRAL",
                    confidence=confidence,
                    gate_result=decision.get("gate_result") or "not_checked",
                    # Phase 3: mark price at decision time (empty when the
                    # context had no mark price for the symbol).
                    entry_price=entry_price,
                    # Only an ENTER decision opens a position worth tracking to
                    # resolution; every other action is inherently "no open
                    # position from this decision".
                    outcome="open" if action == "ENTER" else "flat",
                )
            )
            # Stash the DB id back on the decision dict so the execution
            # path (_execute_ai_action) can flip `executed=1` after a
            # confirmed fill, instead of leaving every row at 0.
            decision["db_id"] = decision_id
            return decision_id
        except Exception as exc:
            self._log.warning("ai_decision_db_log_error", error=str(exc))
            return None

    async def _reconcile_decision_outcomes(self, positions: Any) -> None:
        """Resolve open ENTER decision outcomes against the live position set.

        There is no repository-level close path: positions close on the
        exchange via the STOP_LOSS / TAKE_PROFIT bracket orders attached at
        entry (``execution.engine``), and the fill reconciler only detects
        discrepancies.  So each cycle we compare unresolved ENTER decisions
        (``outcome='open'``) against the live open positions and mark any
        whose symbol no longer has an open position as resolved.

        The close happened off-process, so realized PnL / exit price are not
        available locally; the outcome is marked ``"flat"`` so the row stops
        being treated as open.  The Phase-2 metrics module can backfill actual
        win/loss from trade history.

        Parameters
        ----------
        positions:
            The live open positions fetched this cycle.
        """
        if self._db_manager is None:
            return

        from quad.persistence.repositories import DecisionRepository, make_repo
        from quad.types.domain import PositionStatus

        open_symbols = {
            (getattr(p, "symbol", "") or getattr(p, "contract_symbol", ""))
            for p in positions
            if getattr(p, "status", None) == PositionStatus.OPEN
        }

        repo = make_repo(DecisionRepository, self._db_manager, self._config_dict)
        unresolved = await repo.get_unresolved()
        now = int(time.time())
        for dec in unresolved:
            if dec.symbol in open_symbols:
                continue  # position still open; keep unresolved
            self._log.info(
                "decision_outcome_resolved",
                decision_id=dec.id,
                symbol=dec.symbol,
                action=dec.action,
            )
            await repo.mark_outcome(
                decision_id=dec.id,
                outcome="flat",
                resolved_at=now,
            )

    async def _compute_ai_metrics(self) -> None:
        """Compute and log prediction-quality metrics over resolved decisions.

        Phase 3: pulls resolved (non-``'open'``) decisions via
        ``DecisionRepository.get_resolved``, feeds them to
        ``quad.ai.metrics.compute_metrics`` (hit rate, Expected Calibration
        Error, Brier score), and logs the result on a config-gated interval.
        See ``quad.ai.metrics`` for the win/loss/flat semantics.

        Cost control (kept deliberately lightweight):
        - Runs every ``metrics.interval_cycles`` main cycles (default 1).
        - Skips logging when fewer than ``metrics.min_resolved`` directional
          rows exist (default 5).
        - The work is one indexed SELECT plus in-memory arithmetic — no
          network, no exchange calls.

        Known limitation (flagged intentionally): ``_reconcile_decision_outcomes``
        marks every disappeared symbol ``'flat'``, conflating "closed at
        breakeven" with "symbol rotation moved on while the decision was still
        open".  Because realized PnL is not backfilled (no income-history API,
        no local close path), win/loss labels are not yet assigned, so the
        directional count is typically 0 and the ratio metrics log as ``None``
        until a real close source lands.
        """
        if self._db_manager is None:
            return

        metrics_cfg = self._config_dict.get("ai", {}).get("metrics", {})
        if not metrics_cfg.get("enabled", True):
            return

        interval = int(metrics_cfg.get("interval_cycles", 1) or 1)
        interval = max(interval, 1)
        if self._metrics_cycle_count % interval != 0:
            return

        min_resolved = int(metrics_cfg.get("min_resolved", 5) or 0)
        only_directional = bool(metrics_cfg.get("only_directional", True))

        try:
            from quad.ai.metrics import compute_metrics
            from quad.persistence.repositories import DecisionRepository, make_repo

            repo = make_repo(DecisionRepository, self._db_manager, self._config_dict)
            resolved = await repo.get_resolved(
                limit=2000,
                only_directional=only_directional,
            )
            m = compute_metrics(resolved)
            if m.directional_count < min_resolved:
                self._log.debug(
                    "ai_metrics_skipped",
                    directional_count=m.directional_count,
                    min_resolved=min_resolved,
                    resolved_count=m.resolved_count,
                    flat_count=m.flat_count,
                    open_count=m.open_count,
                )
                return

            self._log.info(
                "ai_decision_metrics",
                sample_count=m.sample_count,
                resolved_count=m.resolved_count,
                directional_count=m.directional_count,
                wins=m.wins,
                losses=m.losses,
                flat_count=m.flat_count,
                open_count=m.open_count,
                hit_rate=round(m.hit_rate, 4) if m.hit_rate is not None else None,
                ece=round(m.ece, 4) if m.ece is not None else None,
                brier=round(m.brier, 4) if m.brier is not None else None,
                mean_confidence=(
                    round(m.mean_confidence, 4)
                    if m.mean_confidence is not None
                    else None
                ),
                n_bins=len(m.ece_bins),
            )

            if self._metrics is not None:
                self._metrics.set_gauge(
                    "ai_hit_rate",
                    m.hit_rate if m.hit_rate is not None else float("nan"),
                )
                self._metrics.set_gauge(
                    "ai_ece",
                    m.ece if m.ece is not None else float("nan"),
                )
                self._metrics.set_gauge(
                    "ai_brier",
                    m.brier if m.brier is not None else float("nan"),
                )
                self._metrics.set_gauge(
                    "ai_decisions_resolved", float(m.resolved_count)
                )
                self._metrics.set_gauge(
                    "ai_decisions_directional", float(m.directional_count)
                )
        except Exception as exc:
            self._log.warning("ai_metrics_compute_failed", error=str(exc))
