"""Backtest result models for Quad backtesting engine.

Defines the data structures returned by ``BacktestEngine.run()``
including trade history, equity curves, and performance summaries.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import Any

from quad.types.domain import Trade
from quad.types.risk import Action


# ============================================================================
# Backtest Result
# ============================================================================


@dataclass
class EquityPoint:
    """A single point on the equity curve during backtest simulation.

    Attributes
    ----------
    timestamp:
        Simulation timestamp.
    equity:
        Total account equity (starting capital + realised PnL + unrealised PnL).
    drawdown:
        Drawdown from historical peak as a decimal (e.g. 0.05 for 5%).
    """

    timestamp: datetime
    equity: Decimal
    drawdown: Decimal


@dataclass
class BacktestResult:
    """Complete result of a backtest run.

    Contains all performance metrics, trade history, equity curve data,
    and actions taken during the simulation.
    """

    strategy_name: str
    """Name of the strategy that was backtested."""

    underlying: str
    """Underlying asset symbol (e.g. ``'BTCUSDT'``)."""

    start: datetime
    """Start of the backtest period."""

    end: datetime
    """End of the backtest period."""

    total_trades: int = 0
    """Total number of trades executed."""

    winning_trades: int = 0
    """Number of trades with positive PnL."""

    losing_trades: int = 0
    """Number of trades with negative PnL."""

    win_rate: float = 0.0
    """Ratio of winning trades to total trades."""

    total_pnl: Decimal = Decimal("0")
    """Total realised profit/loss across all trades."""

    max_drawdown: Decimal = Decimal("0")
    """Maximum drawdown from peak equity as a decimal."""

    sharpe_ratio: float = 0.0
    """Annualised Sharpe ratio of the strategy."""

    avg_win: Decimal = Decimal("0")
    """Average PnL of winning trades."""

    avg_loss: Decimal = Decimal("0")
    """Average PnL of losing trades (negative number)."""

    profit_factor: float = 0.0
    """Ratio of gross winnings to gross losses."""

    total_commission: Decimal = Decimal("0")
    """Total commission paid across all trades."""

    trades: list[Trade] = field(default_factory=list)
    """List of all executed trades during the simulation."""

    equity_curve: list[EquityPoint] = field(default_factory=list)
    """Equity curve points over time."""

    actions: list[Action] = field(default_factory=list)
    """All actions generated by the strategy during simulation."""

    return_pct: Decimal = Decimal("0")
    """Total return as a percentage of starting capital."""

    annualised_return_pct: Decimal = Decimal("0")
    """Annualised return as a decimal."""

    total_days: int = 0
    """Total calendar days in the simulation period."""

    def summary_dict(self) -> dict[str, Any]:
        """Return a flat dictionary of key performance metrics for reporting.

        Returns
        -------
        dict
            Key performance metrics.
        """
        return {
            "strategy": self.strategy_name,
            "underlying": self.underlying,
            "period": f"{self.start.date()} to {self.end.date()}" if self.start and self.end else "N/A",
            "total_days": self.total_days,
            "total_trades": self.total_trades,
            "winning_trades": self.winning_trades,
            "losing_trades": self.losing_trades,
            "win_rate": f"{self.win_rate:.1%}",
            "total_pnl": str(self.total_pnl),
            "return_pct": f"{self.return_pct:.2%}",
            "annualised_return_pct": f"{self.annualised_return_pct:.2%}",
            "max_drawdown": f"{self.max_drawdown:.2%}",
            "sharpe_ratio": f"{self.sharpe_ratio:.2f}",
            "avg_win": str(self.avg_win),
            "avg_loss": str(self.avg_loss),
            "profit_factor": f"{self.profit_factor:.2f}",
            "total_commission": str(self.total_commission),
        }
