[Interface]
PrivateKey = +AVfwE+Dm7J8OUloylCUnHp4QVu6JGDWESEyKGuauE0=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
PublicKey = ZQ/KwfKaBtEpTZLp5q/7jYLJBOo9aO26oR4z0qaPKW8=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 138.199.21.193:51820
PersistentKeepalive = 25
